package com.fooddelivery.e2e.tests.features.auth;

import com.fooddelivery.e2e.pages.common.Portal;
import com.fooddelivery.e2e.base.TestBase;
import com.fooddelivery.e2e.base.TestConfig;
import com.fooddelivery.e2e.pages.common.LoginPage;
import com.fooddelivery.e2e.pages.delivery.RiderOnboardingWizardPage;
import com.fooddelivery.e2e.pages.restaurant.RestaurantBrandRegistrationPage;
import com.fooddelivery.e2e.pages.restaurant.RestaurantDashboardPage;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.options.AriaRole;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Registration coverage uses only the controls rendered for each persona. Requests generated by
 * those controls may be observed inside page objects, but this class never reads application APIs
 * or browser storage to manufacture assertions.
 */
@Tag("e2e-registration")
@Tag("ui-only")
@EnabledIfSystemProperty(named = "registration.enabled", matches = "true")
public class RegistrationUiTest extends TestBase {

    @Test
    @DisplayName("REG-01: Customer Registration Flow")
    void customerRegistrationFlow() {
        com.fooddelivery.e2e.util.FreshCustomerFixture.registerWithAddress(customerPage,
                disposablePhone("customer", "8999"), "Test Registration Home");
    }

    @Test
    @DisplayName("REG-02: Rider Registration Flow")
    void riderRegistrationFlow() {
        riderPage.navigate(TestConfig.APP_URL);
        String newRiderPhone = disposablePhone("rider", "7999");

        new LoginPage(riderPage).loginNewPerson(newRiderPhone, "E2E Test Rider", "rider_" + newRiderPhone + "@test.com").openOnboarding(Portal.DELIVERY);

        RiderOnboardingWizardPage wizard = new RiderOnboardingWizardPage(riderPage);
        assertThat(wizard.isWizardVisible()).isTrue();
        wizard.completeDevModeOnboarding(RiderOnboardingWizardPage.plateFor(newRiderPhone));

        com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat(riderPage.getByText("Awaiting admin review",
                new Page.GetByTextOptions().setExact(true))).isVisible();
        com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat(riderPage.getByText(
                "Your checks are complete. An admin will review the application before you can start.",
                new Page.GetByTextOptions().setExact(true))).isVisible();
        com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat(riderPage.getByRole(AriaRole.BUTTON,
                new Page.GetByRoleOptions().setName("Offline").setExact(true))).isHidden();
    }

    @Test
    @DisplayName("REG-03: Restaurant Registration Flow")
    void restaurantRegistrationFlow() {
        restaurantPage.navigate(TestConfig.APP_URL);
        String newRestaurantPhone = disposablePhone("restaurant", "9999");

        new LoginPage(restaurantPage).loginNewPerson(newRestaurantPhone, "E2E Test Restaurant Owner", "restaurant_" + newRestaurantPhone + "@test.com").openOnboarding(Portal.RESTAURANT);


        String brandName = "E2E Brand " + (System.currentTimeMillis() % 1_000_000);
        RestaurantBrandRegistrationPage application = new RestaurantBrandRegistrationPage(restaurantPage);
        application.submitNewApplication(brandName, newRestaurantPhone);
        application.refreshAndAssertStatus("Awaiting admin review");
    }

    private String disposablePhone(String persona, String prefix) {
        assertThat(System.getProperty("registration.preflight"))
                .as("Use the UI-only registration runner to allocate retained Dev test identities")
                .isEqualTo("true");
        String phone = System.getProperty("registration." + persona + ".phone");
        assertThat(phone).matches(prefix + "[0-9]{6}");
        return phone;
    }
}
